### ISSUE TITLE
list 

### ISSUE THREAD

**Issue by DaGuangDaGuang** [guanyuezhen/A2Net#2]
作者，你好！你可以具体展示以下list文件夹下面的.txt文件的内容吗，我不是特别理解ls -R ./label/* > test.txt，是把A，B，label这三个文件夹里的图片的名称都放入这一个txt文件里面吗

**Comment by guanyuezhen** [comment]
> 作者，你好！你可以具体展示以下list文件夹下面的.txt文件的内容吗，我不是特别理解ls -R ./label/* > test.txt，是把A，B，label这三个文件夹里的图片的名称都放入这一个txt文件里面吗
![image](https://user-images.githubusercontent.com/31332365/230755977-59ed583a-40d3-499f-a47e-da69bee20144.png)
