### ISSUE TITLE
batchsize

### ISSUE THREAD

**Issue by DaGuangDaGuang** [guanyuezhen/A2Net#3]
Why as the batch_size decreases, the training time also decreases, shouldn't it be that the larger the batch_size, the smaller the training time?The time cost is 2.118h when the batch_size is 16 and 3.926h when the batch_size is 32.

**Comment by vdsw** [comment]
Hello! I would like to recur your code ,Would you mind giving me the WHU-CD dataset you've already processed? My email address is [1397173716@qq.com](mailto:1397173716@qq.com) . Thank you very much!

**Comment by guanyuezhen** [comment]
> Hello! I would like to recur your code ,Would you mind giving me the WHU-CD dataset you've already processed? My email address is [1397173716@qq.com](mailto:1397173716@qq.com) . Thank you very much!

You can download the processed dataset from https://drive.google.com/file/d/1VrdQ-rxoGVM_8ecA-ObO0u-O8rSTpSHA/view?usp=sharing

**Comment by vdsw** [comment]
You are so kind!
