### ISSUE TITLE
About loss and F1 for an image pair which has exact same image

### ISSUE THREAD

**Issue by cubicimage** [guanyuezhen/A2Net#6]
Thanks for your great work!

I prepared a image dataset for training and testing. Besides the change dataset, which contains many changed image pairs. It also contains some image pair without changes, the label of which is all black pixels because there isn't any change. I did this in order to let the net to learn both changing and non-changing situations. 

But! I found that the all black pixel label will cause F1 become 0, and big loss. This is not out expectation! We thought the images are the same, the ground thuth label image is black, then the output should be black either.

Is there something wrong with the Loss function?  Sorry for my misunderstanding!

Thanks!

**Comment by guanyuezhen** [comment]
The denominator of Dice loss is added with a very little positive value to avoid the denominator becoming zeros.
